packages:
  - packages/*

catalog:
  typescript: ^5.9.3

catalogs:
  build:
    vite: ^7.3.1
    vite-tsconfig-paths: ^5.1.4
  test:
    '@vitest/coverage-v8': ^4.0.18
    vitest: ^4.0.18

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - lefthook
  - sharp
  - workerd
