packages:
  - packages/*
  - app

allowBuilds:
  '@swc/core': true
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true

catalog:
  typescript: ^5.9.3

catalogs:
  build:
    vite: ^7.3.3
    vite-tsconfig-paths: ^5.1.4
  test:
    '@vitest/coverage-v8': ^4.1.5
    vitest: ^4.1.5

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - lefthook
  - sharp
  - workerd
