[tasks.setup]
description = "Setup"
run = [
    "cargo install wasm-bindgen-cli"
]

[tasks."wasm:build"]
description = "Build wasm"
run = [
    "cargo build --target wasm32-unknown-unknown --release",
    "wasm-bindgen target/wasm32-unknown-unknown/release/motion_core.wasm --out-dir ./pkg --target web"
]

[tasks."wasm:fmt"]
description = "Format wasm source"
run = "cargo fmt"

[tasks."wasm:lint"]
description = "Lint wasm source"
run = "cargo clippy"

[tasks."wasm:check"]
description = "Check wasm source"
run = [
    "cargo fmt",
    "cargo clippy"
]

