[tasks.setup]
description = "Setup"
run = [
    "cargo install wasm-bindgen-cli"
]

[tasks."wasm:build"]
description = "Build wasm"
run = [
    "cargo build --target wasm32-unknown-unknown --release",
    "wasm-bindgen target/wasm32-unknown-unknown/release/motion_core.wasm --out-dir ./pkg --target web"
]

[tasks."wasm:fmt"]
hide = true
run = "cargo fmt"

[tasks."wasm:lint"]
hide = true
run = "cargo clippy"

[tasks."wasm:check"]
hide = true
run = [
    "cargo fmt",
    "cargo clippy"
]

[tasks."ts:fmt"]
hide = true
run = "pnpm format"

[tasks."ts:lint"]
hide = true
run = "pnpm lint"

[tasks."ts:check"]
hide = true
run = "pnpm check"

[tasks.format]
description = "Run format"
run = { tasks = ["wasm:fmt", "ts:fmt"] }

[tasks.lint]
description = "Run lint"
run = { tasks = ["wasm:lint", "ts:lint"] }

[tasks.check]
description = "Run check"
run = { tasks = ["wasm:fmt", "ts:check"] }
