/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteRouteImport } from './routes/works/route'
import { Route as ContactRouteRouteImport } from './routes/contact/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as WorksIdIndexRouteImport } from './routes/works/$id/index'
import { Route as BlogsIdIndexRouteImport } from './routes/blogs/$id/index'

const ContactIndexLazyRouteImport = createFileRoute('/contact/')()
const ContactCompleteIndexLazyRouteImport =
  createFileRoute('/contact/complete/')()

const WorksRouteRoute = WorksRouteRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRouteRoute = ContactRouteRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ContactIndexLazyRoute = ContactIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactRouteRoute,
} as any).lazy(() => import('./routes/contact/index.lazy').then((d) => d.Route))
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksRouteRoute,
} as any).lazy(() => import('./routes/works/index.lazy').then((d) => d.Route))
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blogs/index.lazy').then((d) => d.Route))
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about/index.lazy').then((d) => d.Route))
const ContactCompleteIndexLazyRoute =
  ContactCompleteIndexLazyRouteImport.update({
    id: '/complete/',
    path: '/complete/',
    getParentRoute: () => ContactRouteRoute,
  } as any).lazy(() =>
    import('./routes/contact/complete/index.lazy').then((d) => d.Route),
  )
const WorksIdIndexRoute = WorksIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => WorksRouteRoute,
} as any).lazy(() =>
  import('./routes/works/$id/index.lazy').then((d) => d.Route),
)
const BlogsIdIndexRoute = BlogsIdIndexRouteImport.update({
  id: '/blogs/$id/',
  path: '/blogs/$id/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/blogs/$id/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRouteRouteWithChildren
  '/works': typeof WorksRouteRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/works/': typeof WorksIndexRoute
  '/contact/': typeof ContactIndexLazyRoute
  '/blogs/$id/': typeof BlogsIdIndexRoute
  '/works/$id/': typeof WorksIdIndexRoute
  '/contact/complete/': typeof ContactCompleteIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/works': typeof WorksIndexRoute
  '/contact': typeof ContactIndexLazyRoute
  '/blogs/$id': typeof BlogsIdIndexRoute
  '/works/$id': typeof WorksIdIndexRoute
  '/contact/complete': typeof ContactCompleteIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRouteRouteWithChildren
  '/works': typeof WorksRouteRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/works/': typeof WorksIndexRoute
  '/contact/': typeof ContactIndexLazyRoute
  '/blogs/$id/': typeof BlogsIdIndexRoute
  '/works/$id/': typeof WorksIdIndexRoute
  '/contact/complete/': typeof ContactCompleteIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/works'
    | '/about/'
    | '/blogs/'
    | '/works/'
    | '/contact/'
    | '/blogs/$id/'
    | '/works/$id/'
    | '/contact/complete/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/works'
    | '/contact'
    | '/blogs/$id'
    | '/works/$id'
    | '/contact/complete'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/works'
    | '/about/'
    | '/blogs/'
    | '/works/'
    | '/contact/'
    | '/blogs/$id/'
    | '/works/$id/'
    | '/contact/complete/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRouteRoute: typeof ContactRouteRouteWithChildren
  WorksRouteRoute: typeof WorksRouteRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  BlogsIdIndexRoute: typeof BlogsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexLazyRouteImport
      parentRoute: typeof ContactRouteRoute
    }
    '/works/': {
      id: '/works/'
      path: '/'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof WorksRouteRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/complete/': {
      id: '/contact/complete/'
      path: '/complete'
      fullPath: '/contact/complete/'
      preLoaderRoute: typeof ContactCompleteIndexLazyRouteImport
      parentRoute: typeof ContactRouteRoute
    }
    '/works/$id/': {
      id: '/works/$id/'
      path: '/$id'
      fullPath: '/works/$id/'
      preLoaderRoute: typeof WorksIdIndexRouteImport
      parentRoute: typeof WorksRouteRoute
    }
    '/blogs/$id/': {
      id: '/blogs/$id/'
      path: '/blogs/$id'
      fullPath: '/blogs/$id/'
      preLoaderRoute: typeof BlogsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContactRouteRouteChildren {
  ContactIndexLazyRoute: typeof ContactIndexLazyRoute
  ContactCompleteIndexLazyRoute: typeof ContactCompleteIndexLazyRoute
}

const ContactRouteRouteChildren: ContactRouteRouteChildren = {
  ContactIndexLazyRoute: ContactIndexLazyRoute,
  ContactCompleteIndexLazyRoute: ContactCompleteIndexLazyRoute,
}

const ContactRouteRouteWithChildren = ContactRouteRoute._addFileChildren(
  ContactRouteRouteChildren,
)

interface WorksRouteRouteChildren {
  WorksIndexRoute: typeof WorksIndexRoute
  WorksIdIndexRoute: typeof WorksIdIndexRoute
}

const WorksRouteRouteChildren: WorksRouteRouteChildren = {
  WorksIndexRoute: WorksIndexRoute,
  WorksIdIndexRoute: WorksIdIndexRoute,
}

const WorksRouteRouteWithChildren = WorksRouteRoute._addFileChildren(
  WorksRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRouteRoute: ContactRouteRouteWithChildren,
  WorksRouteRoute: WorksRouteRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  BlogsIdIndexRoute: BlogsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
