name: Run Site Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - ".github/workflows/check-site.yaml"
      - "app/**/*.{ts,tsx}"
      - "app/package.json"

jobs:
  ci-site:
    uses: ./.github/workflows/shared-lint-test.yaml
    with:
      working_directory: 'app'
