name: Run Site Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - ".github/workflows/test_site.yaml"
      - "packages/site/**/*.{ts,tsx}"
      - "packages/site/package.json"

defaults:
  run:
    working-directory: ./packages/site

jobs:
  check:
    name: Lint and type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup

      - name: Run Lint
        run: "pnpm ci:check"

      - name: Run Type Check
        run: "pnpm ci:type"

  test:
    name: Test
    if: |
      github.event.pull_request.draft == false
      && !startsWith(github.head_ref, 'release')
      && !startsWith(github.head_ref, 'doc')

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup

      - name: Run test
        run: "pnpm test:coverage"

      - name: Show coverage
        uses: davelosert/vitest-coverage-report-action@v2
        working-directory: ./packages/site
