name: Run type check and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup.yaml

      - name: Run Lint
        run: "pnpm ci:check"

      - name: Run Type Check
        run: "pnpm ci:type"
