name: Run type check and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.13.1"
          cache: "pnpm"

      - name: setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "10.29.3"

      - name: Install dependencies
        run: pnpm ci

      - name: Run Lint
        run: "pnpm ci:check"

      - name: Run Type Check
        run: "pnpm ci:type"
