name: Run CMS Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - ".github/workflows/check-cms.yaml"
      - "packages/cms/**/*.ts"
      - "packages/cms/package.json"

jobs:
  ci-cms-pack:
    uses: ./.github/workflows/ts-ci.yaml
    with:
      working_directory: 'packages/cms'
      name: 'cms-pack'
