name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup

      - name: Build and deploy
        run: pnpm deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          FORM_API_URL: ${{ secrets.FORM_API_URL }}
